package net.sweenus.simplyskills.registry;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.sweenus.simplyskills.SimplySkills;
import net.neoforged.neoforge.registries.RegisterEvent;

public class SoundRegistry {

    public static SoundEvent FX_SKILL_BACKSTAB;
    public static SoundEvent FX_UI_UNLOCK;
    public static SoundEvent FX_UI_UNLOCK2;
    public static SoundEvent FX_UI_UNLOCK3;
    public static SoundEvent SOUNDEFFECT6;
    public static SoundEvent SOUNDEFFECT7;
    public static SoundEvent SOUNDEFFECT8;
    public static SoundEvent SOUNDEFFECT9;
    public static SoundEvent SOUNDEFFECT10;
    public static SoundEvent SOUNDEFFECT11;
    public static SoundEvent SOUNDEFFECT12;
    public static SoundEvent SOUNDEFFECT13;
    public static SoundEvent SOUNDEFFECT14;
    public static SoundEvent SOUNDEFFECT15;
    public static SoundEvent SOUNDEFFECT16;
    public static SoundEvent SOUNDEFFECT17;
    public static SoundEvent SOUNDEFFECT18;
    public static SoundEvent SOUNDEFFECT19;
    public static SoundEvent SOUNDEFFECT20;
    public static SoundEvent SOUNDEFFECT21;
    public static SoundEvent SOUNDEFFECT22;
    public static SoundEvent SOUNDEFFECT23;
    public static SoundEvent SOUNDEFFECT24;
    public static SoundEvent SOUNDEFFECT25;
    public static SoundEvent SOUNDEFFECT26;
    public static SoundEvent SOUNDEFFECT27;
    public static SoundEvent SOUNDEFFECT28;
    public static SoundEvent SOUNDEFFECT29;
    public static SoundEvent SOUNDEFFECT30;
    public static SoundEvent SOUNDEFFECT31;
    public static SoundEvent SOUNDEFFECT32;
    public static SoundEvent SOUNDEFFECT33;
    public static SoundEvent SOUNDEFFECT34;
    public static SoundEvent SOUNDEFFECT35;
    public static SoundEvent SOUNDEFFECT36;
    public static SoundEvent SOUNDEFFECT37;
    public static SoundEvent SOUNDEFFECT38;
    public static SoundEvent SOUNDEFFECT39;
    public static SoundEvent SOUNDEFFECT40;
    public static SoundEvent SOUNDEFFECT41;
    public static SoundEvent SOUNDEFFECT42;
    public static SoundEvent SOUNDEFFECT43;
    public static SoundEvent SOUNDEFFECT44;
    public static SoundEvent SOUNDEFFECT45;
    public static SoundEvent SOUNDEFFECT46;
    public static SoundEvent SOUNDEFFECT47;
    public static SoundEvent SOUNDEFFECT48;
    public static SoundEvent SPELL_ENERGY;
    public static SoundEvent SPELL_EARTH_PUNCH;
    public static SoundEvent SPELL_MISC_01;
    public static SoundEvent SPELL_FIREBALL;
    public static SoundEvent SPELL_SLASH;
    public static SoundEvent SPELL_SLASH_02;
    public static SoundEvent SPELL_ARCANE_HIT;
    public static SoundEvent SPELL_ARCANE_CAST;
    public static SoundEvent SPELL_GAIN_BARRIER;
    public static SoundEvent SPELL_ARCANE_NOVA;
    public static SoundEvent SPELL_RADIANT_CAST;
    public static SoundEvent SPELL_RADIANT_HIT;
    public static SoundEvent SPELL_RADIANT_EXPIRE;
    public static SoundEvent SPELL_CELESTIAL_CAST;
    public static SoundEvent SPELL_CELESTIAL_HIT;
    public static SoundEvent SPELL_THUNDER_CAST;
    public static SoundEvent SPELL_FIRE_CAST;
    public static SoundEvent SPELL_LIGHTNING_CAST;
    public static SoundEvent ACTIVATE_TOWER_BEACON;
    public static SoundEvent UI_REPLENISH_01;
    public static SoundEvent GONG_WARBLY;
    public static SoundEvent MAGIC_SHAMANIC_POWER_12;
    public static SoundEvent PLACE_STONE_06;
    public static SoundEvent PLACE_STONE_07;
    public static SoundEvent PLACE_STONE_08;
    public static SoundEvent PLACE_STONE_09;
    public static SoundEvent PLACE_STONE_10;
    public static SoundEvent SLASH_02;
    public static SoundEvent DAMAGE_03;
    public static SoundEvent OBJECT_IMPACT_THUD;
    public static SoundEvent OBJECT_IMPACT_THUD_REPEAT;
    public static SoundEvent HIT_03;
    public static SoundEvent MAGIC_SHAMANIC_VOICE_20;
    public static SoundEvent MAGIC_SHAMANIC_SPELL_01;
    public static SoundEvent MAGIC_SHAMANIC_SPELL_02;
    public static SoundEvent MAGIC_SHAMANIC_SPELL_03;
    public static SoundEvent MAGIC_SHAMANIC_SPELL_04;
    public static SoundEvent DARK_WHIRLWIND_WHOOSH;
    public static SoundEvent ENERGY_CHARGE;
    public static SoundEvent MAW;
    public static SoundEvent ACTIVATE_PLINTH_01;

    public static void registerSounds(RegisterEvent event) {
        if (!event.getRegistryKey().equals(Registries.SOUND_EVENT))
            return;

        FX_SKILL_BACKSTAB = register("fx_skill_backstab");
        FX_UI_UNLOCK = register("fx_ui_unlock");
        FX_UI_UNLOCK2 = register("fx_ui_unlock2");
        FX_UI_UNLOCK3 = register("fx_ui_unlock3");
        SOUNDEFFECT6 = register("soundeffect_6");
        SOUNDEFFECT7 = register("soundeffect_7");
        SOUNDEFFECT8 = register("soundeffect_8");
        SOUNDEFFECT9 = register("soundeffect_9");
        SOUNDEFFECT10 = register("soundeffect_10");
        SOUNDEFFECT11 = register("soundeffect_11");
        SOUNDEFFECT12 = register("soundeffect_12");
        SOUNDEFFECT13 = register("soundeffect_13");
        SOUNDEFFECT14 = register("soundeffect_14");
        SOUNDEFFECT15 = register("soundeffect_15");
        SOUNDEFFECT16 = register("soundeffect_16");
        SOUNDEFFECT17 = register("soundeffect_17");
        SOUNDEFFECT18 = register("soundeffect_18");
        SOUNDEFFECT19 = register("soundeffect_19");
        SOUNDEFFECT20 = register("soundeffect_20");
        SOUNDEFFECT21 = register("soundeffect_21");
        SOUNDEFFECT22 = register("soundeffect_22");
        SOUNDEFFECT23 = register("soundeffect_23");
        SOUNDEFFECT24 = register("soundeffect_24");
        SOUNDEFFECT25 = register("soundeffect_25");
        SOUNDEFFECT26 = register("soundeffect_26");
        SOUNDEFFECT27 = register("soundeffect_27");
        SOUNDEFFECT28 = register("soundeffect_28");
        SOUNDEFFECT29 = register("soundeffect_29");
        SOUNDEFFECT30 = register("soundeffect_30");
        SOUNDEFFECT31 = register("soundeffect_31");
        SOUNDEFFECT32 = register("soundeffect_32");
        SOUNDEFFECT33 = register("soundeffect_33");
        SOUNDEFFECT34 = register("soundeffect_34");
        SOUNDEFFECT35 = register("soundeffect_35");
        SOUNDEFFECT36 = register("soundeffect_36");
        SOUNDEFFECT37 = register("soundeffect_37");
        SOUNDEFFECT38 = register("soundeffect_38");
        SOUNDEFFECT39 = register("soundeffect_39");
        SOUNDEFFECT40 = register("soundeffect_40");
        SOUNDEFFECT41 = register("soundeffect_41");
        SOUNDEFFECT42 = register("soundeffect_42");
        SOUNDEFFECT43 = register("soundeffect_43");
        SOUNDEFFECT44 = register("soundeffect_44");
        SOUNDEFFECT45 = register("soundeffect_45");
        SOUNDEFFECT46 = register("soundeffect_46");
        SOUNDEFFECT47 = register("soundeffect_47");
        SOUNDEFFECT48 = register("soundeffect_48");
        SPELL_ENERGY = register("spell_energy");
        SPELL_EARTH_PUNCH = register("spell_earth_punch");
        SPELL_MISC_01 = register("spell_misc_01");
        SPELL_FIREBALL = register("spell_fireball");
        SPELL_SLASH = register("spell_slash");
        SPELL_SLASH_02 = register("spell_slash_02");
        SPELL_ARCANE_HIT = register("spell_arcane_hit");
        SPELL_ARCANE_CAST = register("spell_arcane_cast");
        SPELL_GAIN_BARRIER = register("spell_gain_barrier");
        SPELL_ARCANE_NOVA = register("spell_arcane_nova");
        SPELL_RADIANT_CAST = register("spell_radiant_cast");
        SPELL_RADIANT_HIT = register("spell_radiant_hit");
        SPELL_RADIANT_EXPIRE = register("spell_radiant_expire");
        SPELL_CELESTIAL_CAST = register("spell_celestial_cast");
        SPELL_CELESTIAL_HIT = register("spell_celestial_hit");
        SPELL_THUNDER_CAST = register("spell_thunder_cast");
        SPELL_FIRE_CAST = register("spell_fire_cast");
        SPELL_LIGHTNING_CAST = register("spell_lightning_cast");
        ACTIVATE_TOWER_BEACON = register("activate_tower_beacon");
        UI_REPLENISH_01 = register("ui_replenish_01");
        GONG_WARBLY = register("gong_warbly");
        MAGIC_SHAMANIC_POWER_12 = register("magic_shamanic_power_12");
        PLACE_STONE_06 = register("place_stone_06");
        PLACE_STONE_07 = register("place_stone_07");
        PLACE_STONE_08 = register("place_stone_08");
        PLACE_STONE_09 = register("place_stone_09");
        PLACE_STONE_10 = register("place_stone_10");
        SLASH_02 = register("slash_02");
        DAMAGE_03 = register("damage_03");
        OBJECT_IMPACT_THUD = register("object_impact_thud");
        OBJECT_IMPACT_THUD_REPEAT = register("object_impact_thud_repeat");
        HIT_03 = register("hit_03");
        MAGIC_SHAMANIC_VOICE_20 = register("magic_shamanic_voice_20");
        MAGIC_SHAMANIC_SPELL_01 = register("magic_shamanic_spell_01");
        MAGIC_SHAMANIC_SPELL_02 = register("magic_shamanic_spell_02");
        MAGIC_SHAMANIC_SPELL_03 = register("magic_shamanic_spell_03");
        MAGIC_SHAMANIC_SPELL_04 = register("magic_shamanic_spell_04");
        DARK_WHIRLWIND_WHOOSH = register("dark_whirlwind_whoosh");
        ENERGY_CHARGE = register("energy_charge");
        MAW = register("maw");
        ACTIVATE_PLINTH_01 = register("activate_plinth_01");
    }

    private static SoundEvent register(String name) {
        ResourceLocation id = ResourceLocation.fromNamespaceAndPath(SimplySkills.MOD_ID, name);
        return Registry.register(BuiltInRegistries.SOUND_EVENT, id, SoundEvent.createVariableRangeEvent(id));
    }


}
