modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Sweenus/SimplySkills/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simply-skills"
logoFile="assets/simplyskills/icon.png"
authors="Sweenus, Timefall Development"
description='''
A comprehensive skill tree mod with a focus on combat specialisations.
'''

[[mixins]]
config="simplyskills.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="puffish_skills"
type="required"
versionRange="[0.18.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="puffish_attributes"
type="required"
versionRange="[0.8.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="spell_engine"
type="required"
versionRange="[1.10.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="spell_power"
type="required"
versionRange="[1.6.0,)"
ordering="AFTER"
side="BOTH"
